### PR TITLE
Dean/plotly

### PR DESCRIPTION
**Pull request by dastratakos**
This PR adds all of the `plotly.express` components as built-in meerkat components. Each component exposes a few key plotly args for auto-complete and then forwards the rest of the args through `**kwargs`. Additionally, they all have the  `on_click` and `on_select` Endpoints that allow for meerkat interactivity. The main idea is that a plotly express component is created on the Python side and then passed to the Svelte frontend in JSON form using `fig.to_json()`.

In the dev repo, I tested `on_click` and `on_select` for the first 10 components alphabetically and noticed that `DensityContour` and `DensityHeatmap` might need a little more work since the clicking and selecting isn't exactly intuitive.

### CODE REVIEW

**Comment by seyuboglu** [comment]
Looks like its failing some of the linting. Try running `make lint` locally and address the issues (looks like its mostly lines too long)

**Comment by seyuboglu** [comment]
Otherwise looking great

**Comment by dastratakos** [comment]
Thanks for pointing that out. Should be fixed now

**Comment by seyuboglu** [comment]
I think the failing test was just a missing entry in index.js. Added it here https://github.com/HazyResearch/meerkat/pull/321/commits/1e6cfa43a14ecc74ec4de887817c1326a9214c3b

**Pull request merged**
